package function;

import playlist.AllMusicList; // AllMusicList의 Music 순서와 매칭하기 위함
import model.Music;          // Music 모델 import

import java.util.List;

/**
 * 음악 가사 데이터를 제공하는 유틸리티 클래스입니다.
 * (현재는 하드코딩된 시뮬레이션 가사를 제공합니다.)
 */
public class Lyrics {

    // AllMusicList.initializeMusicList()에 정의된 순서와 일치하도록 가사를 배열합니다.
    private static final String[] LYRICS_SIMULATION = {
        // 응급실 - izi
        "후회 하고 있어요 \n"
        + "우리 다투던 그날 \n"
        + "괜한 자존심 때문에 \n"
        + "끝내자고 말을 해버린거야 \n"
        + "금방 볼 줄 알았어 \n"
        + "날 찾길 바랬어 \n"
        + "허나 며칠이 지나도 \n"
        + "아무소식 조차 없어 \n"
        + "항상 내게 너무 잘해줘서 \n"
        + "쉽게 생각했나봐 \n"
        + "이젠 알아 내 고집때문에 \n"
        + "힘들었던 너를 \n"
        + "이 바보야 진짜아니야 \n"
        + "아직도 나를 그렇게 몰라 \n"
        + "너를 가진 사람 나밖에 없는데 \n"
        + "제발 나를 떠나가지마 \n"
        + "언제라도 내 편이되준 너 \n"
        + "고마운 줄 모르고 \n"
        + "철없이 난 멋대로 한거 \n"
        + "용서할 수 없니 \n"
        + "이 바보야 진짜 아니야 \n"
        + "아직도 나를 그렇게 몰라 \n"
        + "너를 가진 사람 \n"
        + "나 밖에 없는데 \n"
        + "제발 떠나가지마 \n"
        + "너 하나만 사랑하는데 \n"
        + "이대로 나를 두고 가지마 \n"
        + "나를 버리지마 \n"
        + "그냥 날 안아줘 \n"
        + "다시 사랑하게 돌아와", 
        
        // 한번 더 이별 - 이창섭 
        "뒤돌아보면 너의 생각을\n"
        + "떠올린 게 언제였더라\n"
        + "숨 가쁘게 사는 건 무디게 했어\n"
        + "끝나지 않을 것만 같던 그리움\n"
        + "모른 척 너란 사람 묻어주던 친구들은\n"
        + "이제는 슬며시 네 안부 전하고\n"
        + "이젠 떨리지 않아 침착히 고개 끄덕인\n"
        + "나의 모습은 널 잊은 걸까\n"
        + "다시 못 보는 너\n"
        + "남의 사람인 너 견디기엔\n"
        + "미칠 것만 같던\n"
        + "이별의 그날들이 떠나가요\n"
        + "추억 너머\n"
        + "그저 기억으로만\n"
        + "지나간 사람으로만\n"
        + "이제는 너라고 말하지 않겠어요\n"
        + "그 어디에 살더라도\n"
        + "제발 나쁜 안부 안 들리게\n"
        + "뒤돌아보면 그대 추억이\n"
       	+ "사라지면 비어 버리는\n"
       	+ "나의 계절들이 맘에 걸려도\n"
       	+ "그리움 멈추는 게 나는 좋아요\n"
       	+ "못 본 척 나의 눈물\n"
       	+ "가려 주던 친구들은\n"
       	+ "이제는 웃으며 그 얘길 꺼내고\n"
       	+ "나도 웃음으로 받아 줄 수 있었던 오늘\n"
       	+ "우리 한 번 더 이별할까요\n"
       	+ "다시 못 볼 그대\n"
       	+ "남의 사람 그대 견디기엔\n"
       	+ "미칠 것만 같던\n"
       	+ "이별의 그날들이 떠나가요\n"
       	+ "추억 너머\n"
       	+ "그저 기억으로만\n"
       	+ "지나간 사람으로만\n"
        + "이젠 그대라고도 말하지 않겠어요\n"
       	+ "이제서야 안녕\n"
   		+ "한 번도 안 했던 말 안녕\n"
        + "다시 올 것 같던\n"
        + "나 혼자만의 오랜 기대였던\n"
        + "그 날들이 내겐 필요 했어요\n"
        + "많은 걸 깨닫게 했던\n"
        + "그 이별을 난 한번 더 오늘 할게요\n"
        + "그 어디에 살더라도\n"
        + "제발 나쁜 안부 안 들리게", 
        
        // 이별하러 가는 길 - 임한별
        "소란한 내 맘을 누군가 볼까봐\n"
        + "애써 웃는 척 해 사실 나는\n"
        + "누구보다 아픈 중인데\n"
        + "많은 날이 지나면 덤덤하게 잊혀지겠지\n"
        + "다시 또 살아가면서\n"
        + "누군갈 사랑하면서 그렇게\n"
        + "이별하러 가는 길 참 맑기도 하다\n"
        + "널 떼러 가는 길 아무 예고 없이\n"
        + "갑자기 맞이할 이별에\n"
        + "많이 힘들지 몰라 미안해\n"
        + "다신 사랑 안 한단 거짓말 뒤로\n"
        + "우는 널 남긴 채 나 차갑게 떠난다\n"
        + "우리 이제는 안녕 안녕\n"
        + "차라리 나를 미워해\n"
        + "화도 못 내는 네게\n"
        + "너무 쉽게 던진 말 그 말\n"
        + "그게 참 가슴에 남아\n"
        + "미안하단 말 못한 게 후회돼\n"
        + "이별하러 가는 길 참 맑기도 하다\n"
        + "널 떼러 가는 길 아무 예고 없이\n"
        + "갑자기 맞이할 이별에\n"
        + "많이 힘들지 몰라 미안해\n"
        + "다신 사랑 안 한단 거짓말 뒤로\n"
        + "우는 널 남긴 채 나 차갑게 떠난다\n"
        + "우리 이제는 안녕 안녕\n"
        + "다 잊어줘 보란듯이 더 잘 살아가줘\n"
        + "차마 하지 못한 말 붙잡아달란 말\n"
        + "우리 사랑한 그 만큼 그 만큼 아파\n"
        + "미치도록 그리울 사랑아\n"
        + "이게 나란 남자야 못 되고 비겁해\n"
        + "널 울게 만들고 또 니 행복을 빌어\n"
        + "우리 이제는 안녕 안녕 안녕", 
        
        // Yours - 데이먼스 이어
        "내가 손을 잡을게\n"
        + "너는 힘을 빼도 돼 \n"
        + "그저 복사꽃 핀 거릴 걷자\n"
        + "\n"
        + "너의 마음이 녹아\n"
        + "우리 밤을 합치면\n"
        + "무너진 달을 세워놓자\n"
        + "\n"
        + "가끔 너의 모습은\n"
        + "봄날의 낮과 밤 같아\n"
        + "따스하다가도 차갑곤 해\n"
        + "\n"
        + "또 넌 맑은 하늘에\n"
        + "내리는 소나기 같아\n"
        + "넌 대체 내게 뭐를 원해\n"
        + "\n"
        + "그대여 난\n"
        + "솔직히 좀 싫어\n"
        + "그대는 내가 없더라도\n"
        + "아무렇지 않은 게\n"
        + "\n"
        + "넌\n"
        + "나의 모든 하루를 바꿔\n"
        + "난 그렇게 또\n"
        + "두 눈을 감고 마네\n"
        + "\n"
        + "그대여 난\n"
        + "솔직히 좀 싫어\n"
        + "그대는 내가 없더라도\n"
        + "아무렇지 않은 게\n"
        + "\n"
        + "넌\n"
        + "나의 모든 하루를 바꿔\n"
        + "난 그렇게 또\n"
        + "두 눈을 감고 마네",
        
        // 나무 - 카더가든
        "인사 하네요 근심없게\n"
        + "나 아름다운 방식으로 \n"
        + "\n"
        + "무딘 목소리와\n"
        + "어설픈 자국들\n"
        + "날 화려하게 장식해줘요\n"
        + "\n"
        + "그대 춤을 추는 나무 같아요\n"
        + "그 안에 투박한 음악은 나예요\n"
        + "네 곁에만 움츠린\n"
        + "두려움들도\n"
        + "애틋한 그림이 되겠죠\n"
        + "그럼 돼요\n"
        + "\n"
        + "웃어 줄래요 사진처럼\n"
        + "수줍은 맘이 다 녹아내리게\n"
        + "\n"
        + "무력한 걸음과\n"
        + "혼잡한 TV 속\n"
        + "세상없이 또 울기도 해요\n"
        + "\n"
        + "그대 춤을 추는 나무 같아요\n"
        + "그 안에 투박한 음악은 나예요\n"
        + "네 곁에만 움츠린\n"
        + "두려움들도\n"
        + "애틋한 그림이 되겠죠\n"
        + "그럼 돼요\n"
        + "\n"
        + "밤새 모아둔 아스라이 쌓인\n"
        + "고운 마음도 다 가져가세요\n"
        + "언제든 꺼내 볼 수 있죠\n"
        + "\n"
        + "그대 춤을 추는 나무 같아요\n"
        + "그 안에 투박한 음악은 나예요\n"
        + "네 곁에만 움츠린\n"
        + "두려움들도\n"
        + "애틋한 그림이 되겠죠\n"
        + "그럼 돼요",
        
        // 좋은 밤 좋은 꿈 - 너드커넥션
        "저 많은 별을 다 세어 보아도\n"
        + "그대 마음은 헤아릴 수 없어요\n"
        + "그대의 부서진 마음 조각들이\n"
        + "차갑게 흩어져 있는 탓에\n"
        + "\n"
        + "그댄 나의 어떤 모습들을\n"
        + "그리도 깊게 사랑했나요\n"
        + "이제 내가 해줄 수 있는 건\n"
        + "좋은 밤 좋은 꿈 안녕\n"
        + "좋은 밤 좋은 꿈 안녕\n"
        + "\n"
        + "시월의 서늘한 공기 속에도\n"
        + "장미향을 난 느낄 수가 있죠\n"
        + "오월 어느 날에 피었던\n"
        + "빨갛던 밤을 기억하거든요\n"
        + "\n"
        + "그댄 나의 어떤 모습들을\n"
        + "그리도 깊게 사랑했나요\n"
        + "이제 내가 해줄 수 있는 건\n"
        + "좋은 밤 좋은 꿈 안녕\n"
        + "\n"
        + "까만 밤이 다 지나고 나면\n"
        + "이야기는 사라질 테지만\n"
        + "이름 모를 어떤 꽃말처럼\n"
        + "그대 곁에 남아 있을게요\n"
        + "\n"
        + "나는 그대 어떤 모습들을\n"
        + "그리도 깊게 사랑했었나\n"
        + "이제 내가 해줄 수 있는 건\n"
        + "좋은 밤 좋은 꿈 안녕",
        
        // 죽일놈 - 다이나믹 듀오
        "너 아까 나한테 왜 그랬어\n"
        + "너 또 왜 그러는데\n"
        + "내가 도대체 어디까지 맞춰야 돼\n"
        + "넌 맨날 그런 식이야\n"
        + "됐어 나 갈게\n"
        + "\n"
        + "너는 뛰쳐나가 차 문을 부술듯이 닫으면서\n"
        + "난 머리를 쳐박고 한숨 쉬어 핸들을 안으면서\n"
        + "이런 광경이 너무 익숙해 이젠\n"
        + "웬만한 싸움에는 상처도 잘 안나 이젠\n"
        + "명품 쇼핑할 때처럼 너무 깐깐해 니 기준은\n"
        + "한번 화나면 뒤끝 장난 아냐\n"
        + "적어도 2주는 가니까\n"
        + "난 성격이 너무 물러서\n"
        + "넌 항상 말해 남자니까 뒤로 좀 물러서\n"
        + "부담돼 니가 내게 결혼을 보채는 것도\n"
        + "난 달인처럼 대화 화제를 돌리는 법도\n"
        + "많이 늘었어\n"
        + "넌 항상 추격하고 나는 도망쳐\n"
        + "솔직히 말할게 난 아직 준비 안 됐어\n"
        + "지쳤어 조금 널 향한 사랑은 도금이\n"
        + "벗겨진 반지처럼 빛이 바랬어\n"
        + "오늘은 이별을 말해야 될 것 같아\n"
        + "지겹거든 너랑 다툴 때마다 항상 하는 말\n"
        + "\n"
        + "내가 죽일 놈이지 뭐\n"
        + "우리가 어긋날 때면\n"
        + "전부 내 탓이지 뭐\n"
        + "마치 죄인인 것처럼\n"
        + "난 한걸음 물러섰어\n"
        + "아무 말도 안해\n"
        + "완벽한 너한테 난\n"
        + "항상 부족한 사람인 걸\n"
        + "\n"
        + "처음엔 쉬웠어 너와 함께라는 게\n"
        + "난 너를 피해 내 자신을 숨기고 또 지웠어\n"
        + "사랑에 취해 내게 기대고\n"
        + "너란 퍼즐에 날 억지로 맞춰 끼웠어\n"
        + "하지만 이제 난 지쳤어\n"
        + "니가 만든 내게 난 숨이 막혀 오는데\n"
        + "넌 점점 더 내게 바라는게 많아졌어\n"
        + "마찰이 잦아졌어\n"
        + "니가 사준 구두굽처럼 사랑이 닳아졌어\n"
        + "니 잔소리는 넥타이처럼 내 목을 조여서\n"
        + "날 얌전하게 만들었지\n"
        + "그래서 그게 좋아 보였어\n"
        + "그때는 속은 한참 뒤틀리고 꼬였어\n"
        + "지금 난 널 만나기 전에 내가 너무 고파\n"
        + "이미 우리 사이 권태라는 벽은 너무 높아\n"
        + "내가 더 잘할게 잘할게하며 발악했던 나지만\n"
        + "오늘은 말할래 이것이 너와 나의 마지막\n"
        + "\n"
        + "내가 죽일 놈이지 뭐\n"
        + "우리가 어긋날 때면\n"
        + "전부 내 탓이지 뭐\n"
        + "마치 죄인인 것처럼\n"
        + "난 한걸음 물러섰어\n"
        + "아무 말도 안해\n"
        + "완벽한 너한테 난\n"
        + "항상 부족한 사람인 걸\n"
        + "\n"
        + "내가 잘할게\n"
        + "내가 잘할게란 말 이젠 두 번 다신 안할게\n"
        + "이 말 안할래\n"
        + "너를 사랑해란 말 이젠 두 번 다신 안할게\n"
        + "내가 잘할게\n"
        + "내게 잘해달란 말 이젠 두 번 다신 안할게\n"
        + "이 말 안할래\n"
        + "그동안 참아왔던 이별을 오늘은 네게 말할래\n"
        + "\n"
        + "I Don't want say no more\n"
        + "내가 죽일 놈이지 뭐\n"
        + "우리가 어긋날 때면\n"
        + "전부 내 탓이지 뭐\n"
        + "마치 죄인인 것처럼\n"
        + "난 한걸음 물러섰어\n"
        + "아무 말도 안해\n"
        + "완벽한 너한텐 난\n"
        + "항상 부족한 사람인 걸\n"
        + "\n"
        + "I Don't want say no more\n"
        + "I Don't want say no more",
        
        // Aqua man - 빈지노
        "어항 속에 갇힌 고기들보다\n"
        + "어쩌면 내가 좀 더 멍청할지 몰라\n"
        + "너가 먹이처럼 던진 문자 몇 통과\n"
        + "너의 부재중 전화는 날 헷갈리게 하지\n"
        + "\n"
        + "너의 미모와 옷 입는 스타일로 미루어 보았을 때 \n"
        + "너의 어장의 크기는 수족관의 scale \n"
        + "단지 너 하나 때문에 \n"
        + "경쟁은 무척 험하고도 아득해\n"
        + "\n"
        + "I wanna be your boy friend not one of your 생선\n"
        + "허나 너에겐 늘 누군가가 옆에 있어\n"
        + "이럴 때일수록 내 이미지를 위해선 \n"
        + "그저 쏘 쿨한 척 하는 게 최선\n"
        + "\n"
        + "임을 알기에 I said have a good time\n"
        + "그날 밤 업데이트 된 너의 페북의 담벼락엔\n"
        + "여전히 물고기들이 하악 하악\n"
        + "당연히 나도 그 중 하나 \n"
        + "\n"
        + "\n"
        + "하루 종일 너란 바닷속을 항해하는 나는 아쿠아맨 \n"
        + "헤엄 헤엄 헤엄 \n"
        + "I'm rolling in the deep inside of you 너의 어장은 너무 캄캄해\n"
        + "헤엄 헤엄 헤엄\n"
        + "\n"
        + "\n"
        + "손에 꼽을 정도로 아주 가끔씩\n"
        + "엉뚱한 시간에 넌 내가 어딘지 묻지\n"
        + "'어디긴 니 마음이지'라는 본심을\n"
        + "속이며 차분하게 말했지 '지금 집' \n"
        + "\n"
        + "심상치 않은 징조, 심장은 보다 신속\n"
        + "혹시 모를 급만남이 꿈처럼 이루어\n"
        + "질 수도 있을 것 같은 느낌이 들어\n"
        + "지금 너의 위치가 어디든 let's bring it on girl\n"
        + "\n"
        + "통장 잔고는 가까스로 위기모면\n"
        + "입을 옷도 이미 정했어 목걸이는 chrome hearts\n"
        + "but you said, 그런 거 아니고 please don't call me no more\n"
        + "oh no\n"
        + "\n"
        + "하루 종일 너란 바닷속을 항해하는 나는 아쿠아맨 \n"
        + "헤엄 헤엄 헤엄 \n"
        + "I'm rolling in the deep inside of you 너의 어장은 너무 캄캄해\n"
        + "헤엄 헤엄 헤엄\n"
        + "\n"
        + "내 가슴은 회처럼 조각이 났지\n"
        + "u don't give a shit about my broken heart\n"
        + "넌 딱 잘라 말했지 손톱깎이 같이\n"
        + "boy , I don't give a shit about your stupid heart\n"
        + "\n"
        + "\n"
        + "bitch you gotta get yo mind right\n"
        + "너의 얼굴과 몸이 영원할까\n"
        + "bitch you gotta get yo mind right\n"
        + "너의 얼굴과 몸이 영원할까\n"
        + "nah",
        
        // D - 딘
        "Love-love the stars\n"
        + "Love-love the moon\n"
        + "\n"
        + "별 다를 것 없이\n"
        + "똑같은 공기\n"
        + "똑같은 침대에서\n"
        + "보이는 천장까지\n"
        + "\n"
        + "왜 별 이유 없이\n"
        + "공허한 건지\n"
        + "그저 몇 시간 째\n"
        + "멍만 때리는 게\n"
        + "\n"
        + "처음에는\n"
        + "배가 고픈가 했었는데\n"
        + "No way no way no way\n"
        + "\n"
        + "요새는 \n"
        + "칸예 새 앨범을 들어도\n"
        + "뻔해 뻔해 뻔해 \n"
        + "\n"
        + "TV를 틀어 놓은 채\n"
        + "채널만 돌려 보네\n"
        + "But bae 별 의미 없네..\n"
        + "\n"
        + "다 너의 반, 반\n"
        + "반의 반의 반도\n"
        + "채워주질 못 하네\n"
        + "채워지지가 않네 Yeah\n"
        + "\n"
        + "딱 너의 반, 반\n"
        + "반의 반이라도 내게 남았더라면\n"
        + "이렇게 붕 떠있지는 않을 텐데..\n"
        + "\n"
        + "너 없는 밤도\n"
        + "달은 떴다는데\n"
        + "보이지 않아\n"
        + "네 생각에 가려진 채 Yeah\n"
        + "\n"
        + "마음이 기운 채로\n"
        + "판단이 설 리가\n"
        + "너 하나 없다고\n"
        + "내가 이럴 리가 없는데\n"
        + "자꾸 그 때로 또 되감기 돼\n"
        + "\n"
        + "네가 있던 자리 \n"
        + "그 자리 위 밤하늘까지 보여\n"
        + "저 반 쪽 짜리 달이\n"
        + "딱 지금 나의 모습 같지\n"
        + "\n"
        + "다 너의 반, 반\n"
        + "반의 반의 반도\n"
        + "채워주질 못 하네\n"
        + "채워지지가 않네 Yeah\n"
        + "\n"
        + "딱 너의 반, 반\n"
        + "반의 반이라도 \n"
        + "내게 남았더라면\n"
        + "이렇게 붕 떠있진 않을 텐데..\n"
        + "\n"
        + "내일의 어둠이 \n"
        + "저 달을 한 입 삼키면\n"
        + "둘이 만들었던 \n"
        + "세계도 더 작아질 텐데..\n"
        + "\n"
        + "그리움만 꽉 차겠지 \n"
        + "지루한 하루들을 보낸 후\n"
        + "보름달 하늘에 뜰 때쯤에는\n"
        + "\n"
        + "우린 하나라고 \n"
        + "떠들고 다닐 때만 해도 \n"
        + "너는 너고 나는 나라는 게\n"
        + "\n"
        + "이렇게도 명확해질지 몰랐어.\n"
        + "서로 생각할 시간. \n"
        + "시간 초과된 기분\n"
        + "\n"
        + "더 지나면 서로 돌아오라고도 못 해\n"
        + "난 지금 돈키호테처럼 \n"
        + "정처 없이 네 사랑을 꿈꾸네\n"
        + "난 네 눈만 봐도\n"
        + "텅 빈 이 맘을 다 채울 텐데\n"
        + "\n"
        + "다 너의 반, 반\n"
        + "반의 반의 반도\n"
        + "채워주질 못 하네\n"
        + "채워지지가 않네 Yeah\n"
        + "\n"
        + "딱 너의 반, 반\n"
        + "반의 반이라도 내게 남았더라면\n"
        + "이렇게 붕 떠있진 않을 텐데..\n"
        + "\n"
        + "Love-love the stars\n"
        + "Love-love the moon\n"
        + "딱 너의 반, 반\n"
        + "반의 반이라도\n"
        + "내게 남았더라면\n"
        + "그랬더라면..",
        
        // All I want for Christmas is you - Mariah Carey
        "I don't want a lot for Christmas \n"
        + "There's just one thing I need \n"
        + "I don't care about the presents \n"
        + "Underneath the Christmas tree \n"
        + "I just want you for my own \n"
        + "More than you could ever know \n"
        + "Make my wish come true... \n"
        + "All I want for Christmas Is you... \n"
        + "I don't want a lot for Christmas \n"
        + "There is just one thing I need \n"
        + "And I don't care about presents \n"
        + "Underneath the Christmas tree \n"
        + "I don't need to hang my stocking \n"
        + "There upon the fireplace \n"
        + "Santa Claus won't make me happy \n"
        + "With a toy on Christmas day \n"
        + "I just want you for my own \n"
        + "More than you could ever know \n"
        + "Make my wish come true \n"
        + "All I want for Christmas is you... \n"
        + "You baby I won't ask for much this Christmas \n"
        + "I won't even wish for snow \n"
        + "and I'm just gonna keep on waiting \n"
        + "Underneath the mistletoe \n"
        + "I won't make a list and send it \n"
        + "To the North Pole for Saint Nick \n"
        + "I won't even stay awake to \n"
        + "Hear those magic reindeer click \n"
        + "'Cause I just want you here tonight Holding on to me so tight What more can I do Baby \n"
        + "all I want for Christmas is you You... \n"
        + "All the lights are shining So brightly everywhere \n"
        + "And the sound of children's Laughter fills the air \n"
        + "And everyone is singing I hear those sleigh bells \n"
        + "ringing Santa won't you bring me the one I really need - won't you please bring my baby to me... \n"
        + "Oh I don't want a lot for Christmas \n"
        + "This is all I'm asking for \n"
        + "I just want to see baby \n"
        + "Standing right outside my door \n"
        + "Oh I just want him for my own \n"
        + "More than you could ever know \n"
        + "Make my wish come true \n"
        + "Baby all I want for Christmas is You...\n"
        + "All I want for Christmas is you baby... (repeat)",
        
        // When I was your man - Bruno Mars
        "Same bed but it feels just a little bit bigger now\n"
        + "Our song on the radio but it dont sound the same\n"
        + "When our friends talk about you, all it does is just tear me down\n"
        + "Cause my heart breaks a little when I hear your name\n"
        + "\n"
        + "It all just sounds like oooooh…\n"
        + "Mmm, too young, too dumb to realize\n"
        + "That I should have bought you flowers\n"
        + "And held your hand\n"
        + "Should have gave you all my hours\n"
        + "When I had the chance\n"
        + "Take you to every party\n"
        + "Cause all you wanted to do was dance\n"
        + "Now my babys dancing\n"
        + "But shes dancing with another man\n"
        + "\n"
        + "My pride, my ego, my needs, and my selfish ways\n"
        + "Caused a good strong woman like you to walk out my life\n"
        + "Now I never, never get to clean up the mess I made, ohh…\n"
        + "And it haunts me every time I close my eyes\n"
        + "\n"
        + "It all just sounds like oooooh…\n"
        + "Mmm, too young, too dumb to realize\n"
        + "That I should have bought you flowers\n"
        + "And held your hand\n"
        + "Should have gave you all my hours\n"
        + "When I had the chance\n"
        + "Take you to every party\n"
        + "Cause all you wanted to do was dance\n"
        + "Now my babys dancing\n"
        + "But shes dancing with another man\n"
        + "\n"
        + "Although it hurts\n"
        + "Ill be the first to say that I was wrong\n"
        + "Oh, I know Im probably much too late\n"
        + "To try and apologize for my mistakes\n"
        + "But I just want you to know\n"
        + "\n"
        + "I hope he buys you flowers\n"
        + "I hope he holds your hand\n"
        + "Give you all his hours\n"
        + "When he has the chance\n"
        + "Take you to every party\n"
        + "Cause I remember how much you loved to dance\n"
        + "Do all the things I should have done\n"
        + "When I was your man\n"
        + "Do all the things I should have done\n"
        + "When I was your man",
        
        // Off my face - Justin Bieber
        "One touch and you got me stoned \n"
        + "Higher than I've ever known \n"
        + "You call the shots and I follow \n"
        + "Sunrise but the night's still young \n"
        + "No words, but we speak in tongues \n"
        + "If you let me, I might say too much \n"
        + "\n"
        + "Your touch blurred my vision \n"
        + "It's your world, and I'm just in it \n"
        + "Even sober I'm not thinkin' straight \n"
        + "'Cause I'm off my face, in love with you \n"
        + "I'm out my head, so into you \n"
        + "And I don't know how you do it \n"
        + "But I'm forever ruined by you, ooh-ooh-ooh \n"
        + "\n"
        + "Can't sleep 'cause I'm way too buzzed \n"
        + "Too late, now you're in my blood \n"
        + "I don't hate the way you keep me up \n"
        + "\n"
        + "Your touch blurred my vision \n"
        + "It's your world, and I'm just in it \n"
        + "Even sober I'm not thinkin' straight \n"
        + "\n"
        + "'Cause I'm off my face, in love with you \n"
        + "I'm out my head, so into you \n"
        + "And I don't know how you do it \n"
        + "But I'm forever ruined by you, ooh-ooh-ooh \n"
        + "\n"
        + "Ooh, ooh-ooh Ooh-ooh-ooh-ooh-ooh-ooh \n"
        + "Ooh-ooh-ooh-ooh Ooh, ooh-ooh \n"
        + "Ooh-ooh-ooh-ooh-ooh-ooh Ooh-ooh-ooh-ooh \n"
        + "'Cause I'm off my face, in love with you \n"
        + "I'm out my head, so into you \n"
        + "And I don't know how you do it \n"
        + "But I'm forever ruined by you, ooh-ooh-ooh \n"
        + "By you, ooh-ooh-ooh",
        
        // Golden - K-pop demon hunters
        "I was a ghost, I was alone, hah\n"
        + "어두워진, hah, 앞길속에 (Ah)\n"
        + "Given the throne, I didn't know how to believe\n"
        + "I was the queen that I'm meant to be\n"
        + "I lived two lives, tried to play both sides\n"
        + "But I couldn't find my own place\n"
        + "Called a problem child 'cause I got too wild\n"
        + "But now that's how I'm getting paid, 끝없이 on stage\n"
        + "I'm done hidin', now I'm shinin' like I'm born to be\n"
        + "We dreamin' hard, we came so far, now I believe\n"
        + "We're goin' up, up, up, it's our moment\n"
        + "You know together we're glowing\n"
        + "Gonna be, gonna be golden\n"
        + "Oh, up, up, up with our voices\n"
        + "영원히 깨질 수 없는\n"
        + "Gonna be, gonna be golden\n"
        + "Oh, I'm done hidin' now I'm shinin' like I'm born to be\n"
        + "Oh, our time, no fears, no lies\n"
        + "That's who we're born to be\n"
        + "Waited so long to break these walls down\n"
        + "To wake up and feel like me\n"
        + "Put these patterns all in the past now\n"
        + "And finally live like the girl they all see\n"
        + "No more hiding, I'll be shining like I'm born to be\n"
        + "'Cause we are hunters, voices strong, and I know I believe\n"
        + "We're goin' up, up, up, it's our moment\n"
        + "You know together we're glowing\n"
        + "Gonna be, gonna be golden\n"
        + "Oh, up, up, up, with our voices\n"
        + "영원히 깨질 수 없는\n"
        + "Gonna be, gonna be golden\n"
        + "Oh, I'm done hidin', now I'm shining like I'm born to be\n"
        + "Oh, our time, no fears, no lies\n"
        + "That's who we're born to be\n"
        + "You know we're gonna be, gonna be golden\n"
        + "We're gonna be, gonna be\n"
        + "Born to be, born to be glowin'\n"
        + "밝게 빛나는 우린\n"
        + "You know that it's our time, no fears, no lies\n"
        + "That's who we're born to be",
        
        // Blue valentine - Nmixx
        "You'll always be my blue valentine\n"
        + "You'll always be my blue valentine\n"
        + "\n"
        + "식어버린 너의 색은 blue\n"
        + "파랗게 멍이 든 my heart\n"
        + "몇 번이고 덧이 나\n"
        + "열이 나 lovesick\n"
        + "이건 such a bad love\n"
        + "\n"
        + "We fight, we sigh, and stop\n"
        + "붉게 타오르다 한순간에 식어가\n"
        + "Rewind, rewind, rewind\n"
        + "언제 그랬냐는 듯이 또 서롤 찾아\n"
        + "\n"
        + "깊게 새긴 상처\n"
        + "비친 red blood\n"
        + "부서진 forever\n"
        + "I can see it now\n"
        + "Can you see it now?\n"
        + "\n"
        + "우린 마치 broken glass on the ground\n"
        + "돌이킬 수 없다 해도\n"
        + "We can figure it out\n"
        + "\n"
        + "If this love is over\n"
        + "다시 뛰어들어 난\n"
        + "이 사랑은 colder\n"
        + "I'll keep the fire lit in mine\n"
        + "\n"
        + "You'll always be my blue valentine\n"
        + "You'll always be my blue valentine\n"
        + "\n"
        + "식어도 타오르는 얼음 속 불꽃\n"
        + "아무 겁도 없이 뻗어버린 손\n"
        + "Hot and icy\n"
        + "But I like it\n"
        + "It's so you\n"
        + "\n"
        + "바뀌어 맘의 weather\n"
        + "몰려온 cloud\n"
        + "외로운 together\n"
        + "I can feel it now\n"
        + "Can you feel it now?\n"
        + "\n"
        + "Rollercoaster처럼\n"
        + "우린 정신없이\n"
        + "흔들려도\n"
        + "돌아갈 걸 알아\n"
        + "So it doesn't matter\n"
        + "\n"
        + "You might be my end game\n"
        + "대가로 얻은 worst pain\n"
        + "(You might be)\n"
        + "\n"
        + "If this love is over\n"
        + "다시 뛰어들어 난\n"
        + "이 사랑은 colder\n"
        + "I'll keep the fire lit in mine\n"
        + "\n"
        + "You'll always be my blue valentine\n"
        + "You'll always be my blue valentine\n"
        + "\n"
        + "붉고 푸른\n"
        + "사랑이란 bruise\n"
        + "낫지는 않길\n"
        + "Cause it's you (yeah)\n"
        + "\n"
        + "If this love is over\n"
        + "다시 뛰어들어 난 (뛰어들어 난)\n"
        + "이 사랑은 colder (colder, yeah)\n"
        + "I'll keep the fire lit in mine\n"
        + "\n"
        + "You'll always be my blue valentine\n"
        + "(Always be, my blue valentine)\n"
        + "You'll always be my blue valentine\n"
        + "\n"
        + "I'm falling over and over and over, ah\n"
        + "You're getting colder and colder and colder\n"
        + "Blue valentine",
        
        // Drama - aespa
        "Ya Ya I'm the Drama\n"
        + "\n"
        + "Ziggy ziggy zag I'm new\n"
        + "'Cause I go biggie biggie bad It's true\n"
        + "날카로운 눈 안에 비친 Toxic\n"
        + "내 본능을 당겨 Zoom\n"
        + "Hold up, What? Oh my god\n"
        + "You say, What? 다쳐 넌\n"
        + "You better watch out\n"
        + "우린 이미 거센 Boom\n"
        + "달려가고 있어 Vroom\n"
        + "\n"
        + "I li-li like me when I roll\n"
        + "Li-li-like me when I'm savage\n"
        + "Li-li-like me when I go\n"
        + "Li-li-likie when I baddest\n"
        + "Hold up 빛을 따라서\n"
        + "달아 다 다 달려나가 Run\n"
        + "Go Finally Ra ta ta ta\n"
        + "다음 세계를 열어 난\n"
        + "\n"
        + "1, 2 It's time to go\n"
        + "후회 없어 난\n"
        + "맞서 난 깨버렸지\n"
        + "날 따라서 움직일 Rules\n"
        + "손끝으로 세상을 두드려 움직여\n"
        + "Yeah I'm coming\n"
        + "\n"
        + "I bring I bring\n"
        + "all the Drama-ma-ma-ma\n"
        + "I bring Drama-ma-ma-ma\n"
        + "With my girls in the back\n"
        + "Girls in the back\n"
        + "Drama\n"
        + "Trauma-ma-ma-ma\n"
        + "I break Trauma-ma-ma-ma\n"
        + "With MY WORLD in the back\n"
        + "나로 시작되는 Drama\n"
        + "(All that)\n"
        + "\n"
        + "Drama-ma-ma-ma\n"
        + "(Bring it that)\n"
        + "Drama-ma-ma-ma\n"
        + "With my girls in the back\n"
        + "Girls in the back Yeah\n"
        + "I break\n"
        + "Trauma-ma-ma-ma\n"
        + "(We them)\n"
        + "Trauma-ma-ma-ma\n"
        + "With MY WORLD in the back\n"
        + "나로 시작되는 Drama\n"
        + "\n"
        + "Drama-ma-ma-ma\n"
        + "Drama-ma-ma-ma (3, 2, 1)\n"
        + "Drama-ma-ma\n"
        + "You know I've been kind of like\n"
        + "\n"
        + "1, 2, 3 깜짝 놀랄 다음 Scene\n"
        + "키를 거머쥔\n"
        + "주인공은 나\n"
        + "4, 3, 2 Going down\n"
        + "쉽게 Through\n"
        + "Deja Vu 같이\n"
        + "그려지는 이미지\n"
        + "날 굳이 막지 말아\n"
        + "이건 내 Drama\n"
        + "도발은 굳이 안 막아\n"
        + "Uh I'm a stunner\n"
        + "\n"
        + "1, 2 It's time to go\n"
        + "타오르는 날 (타는 날)\n"
        + "느껴 난 And I love it\n"
        + "새로워지는 Rules\n"
        + "난 눈을 떠 (두 눈을 떠)\n"
        + "시작된 걸 (넌) 알아 (Now)\n"
        + "It's coming\n"
        + "\n"
        + "I bring I bring\n"
        + "all the Drama-ma-ma-ma\n"
        + "I bring Drama-ma-ma-ma\n"
        + "With my girls in the back\n"
        + "Girls in the back\n"
        + "Drama\n"
        + "Trauma-ma-ma-ma\n"
        + "I break Trauma-ma-ma-ma\n"
        + "With MY WORLD in the back\n"
        + "나로 시작되는 Drama\n"
        + "\n"
        + "Into the REAL WORLD\n"
        + "다가온 Climax\n"
        + "두려워하지 마\n"
        + "You and I\n"
        + "함께 써 내려가는 Story\n"
        + "날 가로막았던 No\n"
        + "한계를 뛰어 넘어 Every day\n"
        + "Oh Imma make it my way\n"
        + "Out of the way Yeah\n"
        + "\n"
        + "I bring I bring\n"
        + "all the Drama-ma-ma-ma\n"
        + "I bring Drama-ma-ma-ma\n"
        + "With my girls in the back\n"
        + "Girls in the back\n"
        + "Drama\n"
        + "Trauma-ma-ma-ma\n"
        + "I break Trauma-ma-ma-ma\n"
        + "With MY WORLD in the back\n"
        + "나와 함께하는 Drama\n"
        + "(All that)\n"
        + "\n"
        + "You know, I'm savage\n"
        + "거침없는 Baddest\n"
        + "나를 둘러싼 Thrill\n"
        + "거친 여정 속의 Drama\n"
        + "(Drama-ma-ma)\n"
        + "내가 깨트릴 모든 Trauma\n"
        + "(Drama-ma-ma)\n"
        + "지금 시작되는 Drama\n"
        + "\n"
        + "Ya Ya 너로 시작될 MY Drama"
    };

    /**
     * Music 객체의 인덱스를 기반으로 가사를 반환합니다.
     * 이 메서드는 AllMusicList의 초기화 순서와 LYRICS_SIMULATION 배열의 순서가 일치할 때 정확합니다.
     * @param index 가사를 찾을 음악의 인덱스
     * @return 해당 인덱스의 가사 문자열, 없으면 null
     */
    public static String getLyricsByIndex(int index) {
        if (index >= 0 && index < LYRICS_SIMULATION.length) {
            return LYRICS_SIMULATION[index];
        }
        return null;
    }

    /**
     * Music 객체의 제목과 가수를 기반으로 가사를 찾아 반환합니다.
     * AllMusicList에서 해당 Music 객체의 인덱스를 찾아 LYRICS_SIMULATION 배열에서 가사를 조회합니다.
     * @param title 찾을 음악의 제목
     * @param artist 찾을 음악의 가수
     * @return 해당 제목과 가수의 가사 문자열, 없으면 "가사를 찾을 수 없습니다." 메시지
     */
    public static String getLyricsByTitleAndArtist(String title, String artist) {
        List<Music> allMusic = AllMusicList.getAllMusic(); // AllMusicList에서 전체 음악 목록을 가져옵니다.
        for (int i = 0; i < allMusic.size(); i++) {
            Music m = allMusic.get(i);
            if (m.getTitle().equals(title) && m.getArtist().equals(artist)) {
                return getLyricsByIndex(i);
            }
        }
        return "가사를 찾을 수 없습니다."; // 일치하는 곡을 찾지 못했을 경우
    }
}
